name: Slither Analysis
on: [push]
jobs:
  SLITHER:
    runs-on: ubuntu-latest
    permissions:
       # required for all workflows
       security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: crytic/slither-action@v0.1.1
        id: slither
        continue-on-error: true
        with:
          target: 'src/'
          sarif: results.sarif
          solc-version: '0.6.2'
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
